version: "3.8"

services:
  api-gateway:
    build: ./core/api-gateway
    ports:
      - "8080:${API_GATEWAY_PORT}"
    depends_on:
      - auth-service
      - user-service
      - health-service
      - life-os-service
      - cognitive-service
      - recommendation-service
      - finance-service
      - learning-service
      - worklife-service
      - relationship-service
      - health-ai-service
      - notification-service
      - logging-service
      - marketplace-service
      - social_feed-service
      - video_streaming-service
      - chat_messaging-service
      - gaming-service
      - content_hub-service
      - events_ticketing-service
      - travel_location-service
      - ar_ai_experience-service
      - groups_community-service
      - influencer_creator-service
      - social_commerce-service
      - viral_engagement-service
      - multimedia-service
      - rtc-service
    restart: unless-stopped
    env_file:
      - ./.env

  # ====== Core Services ======
  auth-service:
    build: ./core/auth-service
    ports:
      - "${AUTH_SERVICE_PORT}:${AUTH_SERVICE_PORT}"
    restart: unless-stopped
    env_file:
      - ./.env

  user-service:
    build: ./core/user-service
    ports:
      - "${USER_SERVICE_PORT}:${USER_SERVICE_PORT}"
    restart: unless-stopped
    env_file:
      - ./.env

  health-service:
    build: ./core/health-service
    ports:
      - "${HEALTH_SERVICE_PORT}:${HEALTH_SERVICE_PORT}"
    restart: unless-stopped
    env_file:
      - ./.env

  life-os-service:
    build: ./core/life-os-service
    ports:
      - "${LIFE_OS_SERVICE_PORT}:${LIFE_OS_SERVICE_PORT}"
    restart: unless-stopped
    env_file:
      - ./.env

  # ====== Specialized Services ======
  cognitive-service:
    build: ./specialized/cognitive_service
    ports:
      - "${COGNITIVE_SERVICE_PORT}:${COGNITIVE_SERVICE_PORT}"
    restart: unless-stopped
    env_file:
      - ./.env

  recommendation-service:
    build: ./specialized/recommendation-service
    ports:
      - "${RECOMMENDATION_SERVICE_PORT}:${RECOMMENDATION_SERVICE_PORT}"
    restart: unless-stopped
    env_file:
      - ./.env

  finance-service:
    build: ./specialized/finance-service
    ports:
      - "${FINANCE_SERVICE_PORT}:${FINANCE_SERVICE_PORT}"
    restart: unless-stopped
    env_file:
      - ./.env

  learning-service:
    build: ./specialized/learning-service
    ports:
      - "${LEARNING_SERVICE_PORT}:${LEARNING_SERVICE_PORT}"
    restart: unless-stopped
    env_file:
      - ./.env

  worklife-service:
    build: ./specialized/worklife-service
    ports:
      - "${WORKLIFE_SERVICE_PORT}:${WORKLIFE_SERVICE_PORT}"
    restart: unless-stopped
    env_file:
      - ./.env

  relationship-service:
    build: ./specialized/relationship-service
    ports:
      - "${RELATIONSHIP_SERVICE_PORT}:${RELATIONSHIP_SERVICE_PORT}"
    restart: unless-stopped
    env_file:
      - ./.env

  health-ai-service:
    build: ./specialized/health-ai-service
    ports:
      - "${HEALTH_AI_SERVICE_PORT}:${HEALTH_AI_SERVICE_PORT}"
    restart: unless-stopped
    env_file:
      - ./.env

  marketplace-service:
    build: ./specialized/marketplace
    ports:
      - "${MARKETPLACE_SERVICE_PORT}:8000"
    restart: unless-stopped
    env_file:
      - ./.env

  social_feed-service:
    build: ./specialized/social_feed
    ports:
      - "${SOCIAL_FEED_SERVICE_PORT}:8000"
    restart: unless-stopped
    env_file:
      - ./.env

  video_streaming-service:
    build: ./specialized/video_streaming
    ports:
      - "${VIDEO_STREAMING_SERVICE_PORT}:8000"
    restart: unless-stopped
    env_file:
      - ./.env

  chat_messaging-service:
    build: ./specialized/chat_messaging
    ports:
      - "${CHAT_MESSAGING_SERVICE_PORT}:8000"
    restart: unless-stopped
    env_file:
      - ./.env

  gaming-service:
    build: ./specialized/gaming
    ports:
      - "${GAMING_SERVICE_PORT}:8000"
    restart: unless-stopped
    env_file:
      - ./.env

  content_hub-service:
    build: ./specialized/content_hub
    ports:
      - "${CONTENT_HUB_SERVICE_PORT}:8000"
    restart: unless-stopped
    env_file:
      - ./.env

  events_ticketing-service:
    build: ./specialized/events_ticketing
    ports:
      - "${EVENTS_TICKETING_SERVICE_PORT}:8000"
    restart: unless-stopped
    env_file:
      - ./.env

  travel_location-service:
    build: ./specialized/travel_location
    ports:
      - "${TRAVEL_LOCATION_SERVICE_PORT}:8000"
    restart: unless-stopped
    env_file:
      - ./.env

  ar_ai_experience-service:
    build: ./specialized/ar_ai_experience
    ports:
      - "${AR_AI_EXPERIENCE_SERVICE_PORT}:8000"
    restart: unless-stopped
    env_file:
      - ./.env

  groups_community-service:
    build: ./specialized/groups_community
    ports:
      - "${GROUPS_COMMUNITY_SERVICE_PORT}:8000"
    restart: unless-stopped
    env_file:
      - ./.env

  influencer_creator-service:
    build: ./specialized/influencer_creator
    ports:
      - "${INFLUENCER_CREATOR_SERVICE_PORT}:8000"
    restart: unless-stopped
    env_file:
      - ./.env

  social_commerce-service:
    build: ./specialized/social_commerce
    ports:
      - "${SOCIAL_COMMERCE_SERVICE_PORT}:8000"
    restart: unless-stopped
    env_file:
      - ./.env

  viral_engagement-service:
    build: ./specialized/viral_engagement
    ports:
      - "${VIRAL_ENGAGEMENT_SERVICE_PORT}:8000"
    restart: unless-stopped
    env_file:
      - ./.env

  multimedia-service:
    build: ./specialized/multimedia
    ports:
      - "${MULTIMEDIA_SERVICE_PORT}:8000"
    restart: unless-stopped
    env_file:
      - ./.env

  rtc-service:
    build: ./specialized/rtc
    ports:
      - "${RTC_SERVICE_PORT}:8000"
    restart: unless-stopped
    env_file:
      - ./.env

  # ====== Utility Services ======
  logging-service:
    build: ./utility/logging-service
    ports:
      - "${LOGGING_SERVICE_PORT}:${LOGGING_SERVICE_PORT}"
    restart: unless-stopped
    env_file:
      - ./.env

  notification-service:
    build: ./utility/notification-service
    ports:
      - "${NOTIFICATION_SERVICE_PORT}:${NOTIFICATION_SERVICE_PORT}"
    restart: unless-stopped
    env_file:
      - ./.env
